---

- name: Install httpd
  ansible.builtin.dnf:
    name:
      - httpd
      - mod_proxy_html
    state: present

- name: Start httpd
  ansible.builtin.service:
    name: httpd
    state: started
    enabled: yes
    
- name: Install configurations
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  notify: restart httpd
  loop:
    - src: backend_proxy.conf.j2
      dest: /etc/httpd/conf.d/backend_proxy.conf
    - src: frontend_routes.conf
      dest: /etc/httpd/conf.d/frontend_routes.conf
