---

- name: Create Pouta VM
  tags: provision
  ansible.builtin.import_playbook: pouta-vm.yml

- name: Configure server
  hosts: mink
  become: true
  tags: setup
  tasks:
    - name: Set timezone
      community.general.timezone:
        name: "Europe/Helsinki"
        
    - name: "Add gunicorn group"
      ansible.builtin.group:
        name: gunicorn
        state: present

    - name: "Add gunicorn user"
      ansible.builtin.user:
        name: gunicorn
        state: present
        generate_ssh_key: yes
        group: gunicorn

    - name: "Ensure directories"
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: "u+rwx,g+rwxs,o+rx"
      loop:
        - "{{ data_root }}"

    - name: "Install core packages"
      ansible.builtin.dnf:
        name:
          - git
          - gcc
          - pip
          - python3-virtualenv
          - python3-devel
          - unzip
          - perl
          
    - name: "Install dev packages"
      ansible.builtin.dnf:
        name:
          - ripgrep
          - emacs
          - vim
          
- name: Install software
  hosts: mink
  become: true
  roles:
    - role: apache
      tags: apache
    - role: sparv
      tags: sparv
    - role: mink-backend
      tags: mink-backend
    - role: mink-frontend
      tags: mink-frontend
    - role: auth
      tags: auth
    # - role: firewall
    #   tags: firewall
