---

- name: "Ensure auth directory"
  ansible.builtin.file:
    path: "{{ auth_dir }}"
    state: directory
    mode: "u+rwx,g+rwxs,o+rx"
      
- name: "Install auth server"
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ auth_dir }}/{{ item.dest }}"
  loop:
    - src: oauth_server.js.j2
      dest: oauth_server.js
    - src: package.json
      dest: package.json
    - src: auth_service_sqlite.js
      dest: auth_service_sqlite.js
  notify: restart auth

- name: Write private key
  copy:
    content: "{{ lookup('passwordstore', 'auth_private_key') }}"
    dest: "{{ auth_dir }}/private_key.pem"
    mode: '0600'
      
- name: Install oauth dependencies
  community.general.npm:
    path: "{{ auth_dir }}"

- name: "Install auth server systemd script"
  ansible.builtin.template:
    src: auth.service
    dest: /etc/systemd/system/auth.service

- name: Start auth server
  systemd:
    name: auth
    state: started
    enabled: yes