---

- name: Install packages
  ansible.builtin.dnf:
    name:
      - memcached
      - socat
      - sqlite
      - time

- name: Install systemd templates
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "/etc/systemd/system/{{ item }}"
  loop:
    - mink-backend.service
    - mink-backend.socket
    - mink-manager.service
    - socat.service

- name: Fetch repo
  ansible.builtin.git:
    repo: "{{ mink_backend_repo }}"
    version: "{{ mink_backend_version }}"
    dest: "{{ mink_backend_dir }}"
    umask: "0022"
  notify: restart mink-backend

- name: Install requirements
  ansible.builtin.pip:
    requirements: "{{ mink_backend_dir }}/requirements.txt"
    virtualenv: "{{ mink_backend_dir }}/venv"

- name: Create dirs
  ansible.builtin.file:
    state: directory
    path: "{{ mink_backend_dir }}/instance/logs"
    
- name: Install config
  ansible.builtin.template:
    src: config.py.j2
    dest: "{{ mink_backend_dir }}/instance/config.py"
  notify: restart mink-backend

- name: Install auth public key
  ansible.builtin.copy:
    src: public_key.pem
    dest: "{{ mink_backend_dir }}/instance/keys/public_key.pem"

- name: start services
  systemd:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop:
    - mink-backend
    - mink-manager
    - socat

