# Default corpus configuration inherited by all Mink corpora.
# Sparv merges this into every corpus config automatically.

korp:
  protected: true
  modes:
    - name: mink
  keep_undefined_annotations: true
  languages:
    - swe
    - eng
    - fin
  remote_host: "mink@{{ groups['korp'][0] }}"
  config_dir: "{{ korp_config_dir }}"
  annotation_definitions:
    # trankit attrs only exist for trankit languages, which all bind <token> to
    # trankit.token, so these are correct for eng/fin/swe and inert elsewhere.
    # There might be a better way to smuggle these in, but I will revisit that..
    trankit.token:trankit.deprel: deprel_trankit
    trankit.token:trankit.ne_type: ne_type_conll
    trankit.token:trankit.ne_part: ner_bioes

cwb:
  remote_host: "mink@{{ groups['korp'][0] }}"
  remote_registry_dir: "{{ cwb_registry_dir }}"
  remote_data_dir: "{{ cwb_data_dir }}"
